name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Checkout completo del repositorio

    # Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Usar Temurin JDK (opción recomendada)
    
    # Verificar la instalación de Java
    - name: Verify Java version
      run: java -version

    # Construir el proyecto con Maven
    - name: Build with Maven
      run: mvn -B package --file Remota_Jenkins/pom.xml
